---
language: python

python:
  - "3.7"

install:
  - >
    pip install -e .[dev]
    --extra-index-url https://${PYPI_USERNAME}:${PYPI_PASSWORD}@eu.artifactory.swg-devops.com/artifactory/api/pypi/res-accelerated-discovery-team-rxn-public-pypi-local/simple
    --extra-index-url https://${PYPI_USERNAME}:${PYPI_PASSWORD}@eu.artifactory.swg-devops.com/artifactory/api/pypi/res-accelerated-discovery-team-rxn-private-pypi-local/simple
  # install RDKit. This is not as a setup dependency in order not to install it
  # in downstream packages and avoid potential conflicts with the conda
  # installation of RDKit
  - pip install rdkit-pypi==2021.3.2

script:
  # Style guide enforcement
  - flake8
  - yapf --quiet --recursive .
  # static typing
  - mypy .
  # Test suite
  - pytest

deploy:
  provider: pypi
  server: https://${PYPI_SERVER}
  distributions: "sdist bdist_wheel"
  username: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  on:
    tags: true

